services:
  - type: web
    name: eventpro-frontend
    buildCommand: VITE_API_URL=https://eventbooking-backend-nmlq.onrender.com/api npm install && npm run build
    startCommand: npm exec serve -s dist -l 3000
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: VITE_API_URL
        value: https://eventbooking-backend-nmlq.onrender.com/api
    publicDir: dist
